Attempt removing abstract profile for comorbidities
Got SUSHI to run but it looks like it's not properly generating
the StructureDefintion that's passed into publisher.jar.

It looks like `conditionCode` slices are being created for each
slice of `component`, but `conditionReference` slices are not being
created by SUSHI. Here's an example from the file generated by SUSHI:

      {
        "id": "Observation.component:alcoholAbuse",
        "path": "Observation.component",
        "sliceName": "alcoholAbuse",
        "short": "Alcohol Abuse Comorbidity",
        "definition": "Component representing the presence or absence of the named comorbidity with optional condition code(s) or reference to the actual condition(s).",
        "min": 0,
        "max": "1"
      },
      {
        "id": "Observation.component:alcoholAbuse.extension",
        "path": "Observation.component.extension",
        "mustSupport": true
      },
      {
        "id": "Observation.component:alcoholAbuse.extension:conditionCode",
        "path": "Observation.component.extension",
        "sliceName": "conditionCode"
      },
      {
        "id": "Observation.component:alcoholAbuse.extension:conditionCode.value[x]",
        "path": "Observation.component.extension.value[x]",
        "binding": {
          "strength": "extensible",
          "valueSet": "http://hl7.org/fhir/us/mcode/ValueSet/elixhauser-alcohol-abuse-vs"
        }
      },
      {
        "id": "Observation.component:alcoholAbuse.code",
        "path": "Observation.component.code",
        "patternCodeableConcept": {
          "coding": [
            {
              "code": "ALCOHOL",
              "system": "http://hl7.org/fhir/us/mcode/CodeSystem/mcode-elixhauser-category"
            }
          ]
        }
      },

Note how there is a JSON element for `Observation.component:alcoholAbuse.extension:conditionCode`
but not `Observation.component:alcoholAbuse.extension:conditionReference.

No errors are shown in the SUSHI output, and when the entire publisher.jar
build process is run, there are a number of errors, which are presumably,
though certainly not definitely, related to the SUSHI output missing the slice.

The .html output from publisher.jar mangles the slicing, as one might expect.

Here are the publisher errors for reference:

ERROR: Bundle/scenario1-mcode-patient-bundle
resource.component[0].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:depression.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Bundle/scenario1-mcode-patient-bundle
resource.component[0].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator

ERROR: Bundle/scenario1-mcode-patient-bundle
resource.component[1].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:hypertensionComplicated.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Bundle/scenario1-mcode-patient-bundle
resource.component[1].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator

ERROR: Observation/mCODECancerRelatedComorbiditiesExample1
Observation.component[0].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:cardiacArrhythmia.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Observation/mCODECancerRelatedComorbiditiesExample1
Observation.component[0].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator

ERROR: Observation/mCODECancerRelatedComorbiditiesExample1
Observation.component[1].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:depression.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Observation/mCODECancerRelatedComorbiditiesExample1
Observation.component[1].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator

ERROR: Observation/scenario1-mcode-cancer-related-comorbidities
Observation.component[0].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:depression.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Observation/scenario1-mcode-cancer-related-comorbidities
Observation.component[0].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator

ERROR: Observation/scenario1-mcode-cancer-related-comorbidities
Observation.component[1].extension[0]:
Slicing cannot be evaluated: Could not match discriminator ([url]) for slice Observation.component:hypertensionComplicated.extension:conditionCode in profile http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-related-comorbidities - the discriminator [url] does not have fixed value, binding or existence assertions

ERROR: Observation/scenario1-mcode-cancer-related-comorbidities
Observation.component[1].extension[0]:
Slicing cannot be evaluated: illegal function name null() in discriminator